name: Generate Word Doc

on:
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-24.04
    container: 
      image: pandoc/latex:latest

    steps:
      # checkout repo contents
      - uses: actions/checkout@v4

      # run pandoc to generate word doc from markdown
      - name: run pandoc
        run: |
          pandoc -f markdown -t docx -o "gh-actions-pandoc-readme.docx" --toc "./README.md" 

      # output generated file to build artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: Word Doc
          path: "gh-actions-pandoc-readme.docx"
